coreos/cargo-vendor-filterer

- src/main.rs
`cargo vendor` only vendors stuff from crates.io; we expect
path dependencies are already included from e.g. a git checkout
of the project.
Closes: https://github.com/cgwalters/cargo-vendor-filterer/issues/1
> Skip non-crates-io packages

- src/main.rs
I missed the case of passing a target vendor directory; we need
to remove the 1st argument before passing it off to clap.
> Fix subcommand + argument

- Cargo.toml
- ci/selftest.sh
- src/main.rs
In some use cases, one wants to e.g. drop vendored C sources
and hence require dynamically linking to the target library.  We
do this in rpm-ostree with `curl-sys`.
> Support excluding paths from crates

- Cargo.lock
- Cargo.toml
- README.md
- ci/selftest.sh
- src/main.rs
For many of our projects we want to attach them to e.g.
Github releases, which is best done as a single file archive.
We spend a bit of effort to make the output of this reproducible.
> Add `--format=tar` and `--format=tar.zstd`

- README.md
- ci/selftest.sh
- src/main.rs
Run `cargo metadata` multiple times and union the set of outputs.
> Add support for multiple platforms

- Cargo.lock
- Cargo.toml
- ci/selftest.sh
- src/main.rs
This way one can more conveniently do e.g.
`platforms: ["*-linux-gnu"]`
Closes: https://github.com/cgwalters/cargo-vendor-filterer/issues/23
> Add support for globs `*` in `platforms`

- README.md
- ci/selftest.sh
- src/main.rs
Our current tar default puts everything at the toplevel,
which is in retrospect surprising given a more standard
practice of including the `vendor/` directory.
For backwards compatibility, keep things as is, but
add a `--prefix=` option which allows configuring this.
Closes: https://github.com/coreos/cargo-vendor-filterer/issues/27
> Add `--prefix=vendor`

- src/main.rs
It is possible to add the following to the Cargo.toml file:
```toml
[dependencies]
tracing-oslog = { git = "https://github.com/kgrech/tracing-oslog", branch = "zero_byte_fix" }
```
In this case ``.cargo-checksum.json`` will look similar to this:
```json
{
"files": {
".editorconfig": "97449e38427d3efc434009cb1ae1942b56daf7b28a942484cb196d94f015b200",
".rustfmt.toml": "113bab55bd151637aa8aad2e0f6de79596d99a82d2e24449d198f6606e6b97ed",
"Cargo.toml": "c74d0e88d99e379665046b4ba7b8a90218f7993280e6c30869f8e283a16f0684",
"LICENSE.md": "b36ff589a7b586161394980ac056831e3795e7390270c9be98bb2fa85829646d",
"README.md": "541e4e5e5c8ac8f5ee4982cc828ac6864bad3e6343e9d9ca324ae7824639df63",
"build.rs": "3cb1a3c31663e69a5331d3a00ffed50b048c85d7fe8c5fb94dc2a87c9f82a125",
"src/ffi.rs": …
```
> Fix the bug in checksum file parsing

- .gitignore
- src/main.rs
This is how my ``Cargo.toml`` looks like:
```
[package]
name = "my_package"
version = "0.1.0"
edition = "2021"
[dependencies]
thiserror = "1.0.30"
tracing = "0.1"
tracing-oslog = { git = "https://github.com/kgrech/tracing-oslog", branch = "main" }
tracing-core = "0.1"
tracing-subscriber = "0.3"
[dev-dependencies]
libc = "0.2"
```
You can see that ``tracing-oslog`` is not fetched from crates-io, but it is fetch from github. I would sill like to vendor it so that I can build my project without connection to internet.
However right now it is not vendored because of the ``.filter(|source| source.is_crates_io())`` line.
I am making an assumption that the idea of this if is not to vendor local dependencies. However if it is a local dependency, then ``source`` for it is already ``None`` and …
> Do not filter against crates io

- src/main.rs
It's really unfortunate that the stdlib doesn't have an ergonomic default API for this.
I noticed this when trying to output to a target with a nonexistent parent directory.
> output: Check the exit code from `tar`

- README.md
- src/main.rs
I'd missed that this exists earlier.  This allows configuring vendoring for full workspaces too.
Closes: https://github.com/coreos/cargo-vendor-filterer/issues/41
> main: Honor workspace metadata

- Cargo.lock
Sigh.  I was using `cargo release` but that fell over for me and I haven't debugged it yet.
> Also update Cargo.lock

- src/main.rs
If we create a `vendor/` directory in many git repositories, it might not be `.gitignored` and hence may cause the IDE to try to monitor all the files.
Instead, if one does `cargo vendor-filterer --format=tar.zstd target/vendor.tar.zstd` as encourged by the docs, we now create the temporary directory in `target` which will be gitignored *and* also automatically cleaned up with `cargo clean`.
> Create tempdir in target basedir

- Cargo.lock
- README.md
- ci/selftest.sh
- src/main.rs
- src/tiers.rs
Depends https://github.com/coreos/cargo-vendor-filterer/pull/63
---
When we originally added support for platform globbing via e.g.
`*-unknown-linux-gnu` it worked with the Rust toolchain at the time.
Later, Rust added `m68k-unknown-linux-gnu` as a tier 3 target, which
is not installed by default.
This broke anyone using globs.
Add support for filtering by tiers; see
https://doc.rust-lang.org/nightly/rustc/platform-support.html
AFAICS, the list isn't available in any machine-readable form,
but it doesn't change often, so hardcode it for now.
This filtering combines with the platform one, which fixes the
bug.
Filtering by tier can also be used independently; this drops out
things like `redox_syscall` for example.
Closes: https://github.com/coreos/cargo-vendor-filterer/issues/50
---
> Add support for `tier` filtering

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- tests/vendor_filterer/format.rs
This gives us support for `--format=tar` and `--format=tar.gz`
on all platforms without an external binary.
For now, `zstd` compression requires an external binary because
the Rust crate still requires an external shared library, which
will be painful for Windows users.
I think this will be OK for MacOS users though since they're likely
to be using homebrew.
It may make sense to have a feature flag for use of external binaries.
---
>  Use `tar` and `flate2` crates

- .github/workflows/ci.yml
We should run the same places as `cargo`.
> ci: Also test on MacOS

- Cargo.lock
- Cargo.toml
- src/main.rs
This will help us know in the future if we add more keys like `tier = "2"` but the user is using a too old binary.
> main: Warn about unknown keys in `Cargo.toml`

- .github/workflows/ci.yml
- src/main.rs
Basically, in the case that there are two versions of a crate:
- foo-1
- foo-2
`cargo vendor` will write directories named:
- `vendor/foo-1`
- `vendor/foo` (meaning `foo-2`)
We weren't handling the case where the *newer* version of these was filtered out.
To correctly handle this, we need to always gather an unfiltered view to know what `cargo vendor` will do, and then build up a mapping from package IDs to that name.
Closes: https://github.com/coreos/cargo-vendor-filterer/issues/75
> Correctly handle filtered-out latest versions

- Cargo.lock
We need to set up dependabot here, but let's catch up on things...
Closes: https://github.com/coreos/cargo-vendor-filterer/issues/79
> cargo update(*)

- src/lib.rs
- src/main.rs
This option is passed down to `cargo vendor`
Fixes #82
> Add `--respect-source-config` option

- .github/workflows/ci.yml
- src/main.rs
This is still not tested if it works.
- Used flag description from `cargo build`:
```
-F, --features <FEATURES>  Space or comma separated list of features to activate
--all-features             Activate all available features
--no-default-features      Do not activate the `default` feature
```
**Reference issues/prs**: #91
> improvement: add option `--no-default-features` and `--features`

- .github/workflows/ci.yml
This is nicer with a clearly split up matrix with arguments; and dropping the version number out of the GHA name avoids us needing to update the branch protection when bumping versions.
> ci: Clean up workflow

- .github/workflows/ci.yml
- .gitignore
- README.md
- src/main.rs
- tests/vendor_filterer/exclude.rs
Add a wildcard option `*` to the existing parameter `--exclude-crate-path` adding a possibility to excluded folders from all crates.
A typical use case is to remove folders `tests`. 
Background:
- the Rust book recommends using this folder for test code: <https://doc.rust-lang.org/book/ch11-03-test-organization.html>
- I do not expect to have a conflict with actual crate name, because there is currently no crate named `*` and even though it is not strictly against [Rust naming conventions](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md), creating a new crate called `*` is against the rule of using words to name things and such a name would be too short (1 character only)
Closes https://github.com/coreos/cargo-vendor-filterer/issues/86
> feat: support a wildcard in exclude crate paths

- README.md
- src/main.rs
- tests/vendor_filterer/toml.rs
I want to exclude `src/smoke.c` from `libz-sys` specifically, as part of a larger goal of supporting filtering out `.c` files for example.
> Support regular files in exclude-crate-paths

- Cargo.lock
- Cargo.toml
- README.md
- src/dep_kinds.rs
- src/dep_kinds_filtering.rs
- src/main.rs
- tests/vendor_filterer/common.rs
- tests/vendor_filterer/exclude.rs
Adds an optional `--dep-kinds` flag allowing to filtering out dev or build dependencies similarly to the edges option in cargo tree (<https://doc.rust-lang.org/cargo/commands/cargo-tree.html>)
Possible values are:
- `all` (default)
- `normal`
- `build`
- `dev`
- `no-normal`
- `no-build`
- `no-dev`
The goal was to modify as little as possible the existing code base and to add the additional filtering only if the optional parameter is set.
Ideally this filter will be added to the cargo metadata, so that the commit can be reworked to apply the filter directly in function `add_packages_for_platform()`
Closes #101
> feat: add optional dep-kind parameter

- src/main.rs
- tests/vendor_filterer/common.rs
- tests/vendor_filterer/sync.rs
- tests/vendor_filterer/toml.rs
- tests/vendor_filterer/versioned_dirs.rs
I have not (yet) made `--versioned-dirs` the default, as I think we might want to have a separate discussion about this.
As I'm not clear on the following question:
Once it's the default, should `--versioned-dirs` be a no-op flag, or should the user still be able to DEactivate that feature? Depending on the answer, we can or can't remove the decision-code I added.
> Fix #106: Fix wrongly filtered out packages when using --versioned-dirs

- .github/workflows/ci.yml
The `unshare` invocation started failing, hopefully this fixes it. In any case we might as well stop using a super old version.
> ci: Bump to ubuntu-24.04, use unshare --propagation=unchanged

- src/lib.rs
- src/main.rs
The core way this project works for filtered crates is to replace them with a "stub" that only has an empty `src/lib.rs`. When processing the manifest previously, we didn't override the `lib` section that might have been present. Usually this worked because of autodiscovery.
But in the corner case that arose recently in cxx where there was a `bin`-only crate as a build dependency, things broke because we dropped the `bin` section but didn't add a `lib`.
Now arguably, there's a bug in `cargo` here because it dropped the dependency in `cargo metadata` but still checks it in `cargo build`.
But anyways it's clearly correct here for us to have a canonical `lib` section always (whether it was present or not in the filtered crate) so do that.
Closes: …
> Always generate + override `[lib]` for filtered crates

- src/dep_kinds_filtering.rs
Some of the test code here was "swallowing" error messages making things unnecessarily hard to debug. Just use `unwrap()` so we know what the real error is.
> tests: Use unwrap instead of match

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- tests/vendor_filterer/exclude.rs
This PR adds glob pattern support to the `exclude` field in `exclude-crate-paths`. 
Now you can exclude files by pattern instead of just exact names:
```toml
exclude-crate-paths = [
{ name = "ring", exclude = "pregenerated/*.o" },
{ name = "*", exclude = "tests" },
{ name = "openssl-sys", exclude = "**/*.a" }
]
```
Helpful in removing build artefacts, platform-specific binaries, and reducing vendor directory size without having to list every single file.
Backwards compatible - existing exact path exclusions continue to work unchanged.
Fixes #122
> feat: support glob patterns in exclude-crate-paths (#122)

- Cargo.lock
- Cargo.toml
- src/main.rs
- tests/vendor_filterer/format.rs
Add `sha-rs` and `openssl` features and use the sha2 crate for SHA-256 by default. Avoiding openssl dependency can be occasionally very convenient.
> Use `sha2` crate for SHA-256 by default
